---
title: "Material introdutório de Processamento Digital de Imagens e Visão Computacional"
author: ""
lang: pt-BR
site: bookdown::bookdown_site
knit: "bookdown::render_book"
bibliography: book.bib
csl: ieee.csl
link-citations: yes
documentclass: book
---

# Início {-}

Esse site foi desenvolvido pelo grupo **COVAP** (Computação Visual Aplicada) que visa oferecer um material introdutório da disciplina de PDI (Processamento Digital de Imagens) e VC (Visão Computacional) para alunos e entusiastas no assunto.
Os conteúdos se encontram organizados na seguinte estrutura:

- [Introdução](#intro)
- [Formação da imagem](#formacaoImagem)
- [Transformações geométricas](#transformacoesGeometricas)
- [Transformações radiométricas](#transformacoesRadiometricas)
- [Filtros Digitais](#filtros)
- [Segmentação](#segmentacao)
- [Separação plano de fundo](#separacaoFundo)
- [Deep Learning](#deepLearning)
  - [CNN](#cnn)

Lembramos ainda que todo o material está hospedado no [Github](https://github.com/covap-utfpr/pdi), agradeçemos então todo apontamento de erros e sugestões, para que assim consigamos sempre disponibilizar um conteúdo revisado e livre de quaisquer erros.

<!-- If you need PDF output, uncomment bookdown::pdf_book above in YAML. You will need a LaTeX installation, e.g., https://yihui.name/tinytex/ -->
